ALTER TABLE sesiones_ejecucion ADD COLUMN IF NOT EXISTS tipo_simulacion VARCHAR(20) NOT NULL DEFAULT 'VENTANA_FIJA';
ALTER TABLE sesiones_ejecucion ADD COLUMN IF NOT EXISTS ventana_horas INT NOT NULL DEFAULT 4;
ALTER TABLE sesiones_ejecucion ADD COLUMN IF NOT EXISTS duracion_dias INT NOT NULL DEFAULT 5;
